# Generated by Django 5.0.1 on 2024-01-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together=set(),
        ),
    ]
