# Generated by Django 5.0.1 on 2024-01-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval', '0002_alter_loan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
