# Generated by Django 5.0.1 on 2024-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
